# ~/.config/tmux/tmux.conf
set -g default-terminal "tmux-256color"

# Enable CSI-u shortcuts for nvim
set -as terminal-features 'xterm-kitty:extkeys'
set -s extended-keys on

# True colors
set -g terminal-overrides ",*:Tc"

# Styles
set -g status-style "bg=#8ac6f2,fg=black"
set -g pane-active-border-style fg='#f5abb9'
set -g pane-border-style fg=white

set -g default-shell /bin/zsh
set -g history-limit 999999
set -g mode-keys vi
set -g mouse on

set -g repeat-time 500

# Rebind: C-b o -> C-b e
bind 'e' select-pane -t :.+

# Rebind splits with preserve pwd
bind '\' split-window -h -c '#{pane_current_path}'  # Split panes horizontal
bind '-' split-window -v -c '#{pane_current_path}'  # Split panes vertically

# Source new settings (doesn't unset/unbind old bindings)
bind 'k' source-file ~/.config/tmux/tmux.conf

######## TMUX SCROLL ########
# 1. enter copy-mode with wheelup
# works for:      shell
# doesn't work:   VIM, LESS, MAN
bind -n WheelUpPane \
	if-shell -Ft = "#{mouse_any_flag}" \
		"send -M" \
		"if-shell -Ft= '#{pane_in_mode}' \
			'send -M' 'copy-mode -e'"

# 2.
# works for       VIM, LESS
# Emulate scrolling by sending up and down keys if these commands are running in the pane
#tmux_commands_with_legacy_scroll="less man vim vi git more nano"
#
#bind -T root WheelUpPane \
#	if-shell -Ft= '#{?mouse_any_flag,1,#{pane_in_mode}}' \
#		'send -Mt=' \
#		'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
#			"send -t= Up" "copy-mode -et="'
#
#bind -T root WheelDownPane \
#	if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
#		'send -Mt=' \
#		'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
#			"send -t= Down" "send -Mt="'
